// Variables para el API REST

// URL
const API_URL = process.env.REACT_APP_API_URL;

// URL USUARIOS
const API_URL_USUARIOS = API_URL + process.env.REACT_APP_API_USUARIOS;

// URL CATEGORIAS
const API_URL_CATEGORIAS = API_URL + process.env.REACT_APP_API_CATEGORIAS;

// URL PRODUCTOS
const API_URL_PRODUCTOS = API_URL + process.env.REACT_APP_API_PRODUCTOS;

// URL VENTAS
const API_URL_VENTAS = API_URL + process.env.REACT_APP_API_VENTAS;

// URL PROVEEDORES
const API_URL_PROVEEDORES = API_URL + process.env.REACT_APP_API_PROVEEDORES;

// URL VENTAS
const API_URL_PEDIDOS = API_URL + process.env.REACT_APP_API_PEDIDOS;

// Exportamos
export {
  API_URL,
  API_URL_USUARIOS,
  API_URL_PRODUCTOS,
  API_URL_CATEGORIAS,
  API_URL_VENTAS,
  API_URL_PEDIDOS,
  API_URL_PROVEEDORES
};
